In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.externals import joblib
from sklearn.metrics import mean_squared_error

c:\users\kevin song\miniconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)

In [2]:
np.random.seed(0)

In [3]:
data = pd.read_csv("validation.csv.txt", low_memory = False)

In [4]:
data = data.drop(["parcel"], axis = 1)

In [5]:
data

,location,use,heat,walls,roof,class,condition,quality,cool,landclass,...,bath_fixture,stories,rooms,landmeas,fcv_16,fcv_17,fcv_18,fcv_19,fcv_20,fcv_21
0,102,8,8,3,7,2,0,0,1,0,...,3.0,1.0,3.0,3920.0,38000,45956,48305,57189,70102,77546.0
1,102,8,8,3,7,2,1,0,1,0,...,3.0,1.0,6.0,4760.0,75681,68113,71594,84763,108011,119481.0
2,102,8,1,3,7,2,0,0,1,1,...,3.0,1.0,5.0,1.0,81320,73188,76929,91078,112637,124599.0
3,102,8,1,4,1,2,0,0,1,1,...,3.0,1.0,5.0,1.0,97047,87342,91806,108693,130794,144684.0
4,102,8,6,2,1,2,1,0,1,0,...,3.0,1.0,5.0,1.0,84616,76154,80047,94770,116660,129049.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101656,102,15,1,7,1,3,1,1,1,0,...,6.0,1.0,5.0,1.0,122159,122159,126724,144980,162070,180771.0
101657,102,8,1,2,1,2,0,0,1,1,...,3.0,1.0,4.0,1.0,71496,64346,67635,80076,97082,107391.0
101658,102,15,1,7,3,3,2,1,1,0,...,6.0,1.0,5.0,1.0,96747,96482,99815,113887,127454,141774.0
101659,102,15,1,2,3,3,1,1,1,0,...,3.0,1.0,4.0,1.0,92794,92794,96261,110129,124338,138685.0
101660,102,8,1,2,1,2,1,1,1,0,...,6.0,1.0,6.0,1.0,105133,94620,99456,117749,144151,159459.0

In [6]:
fcv_21 = data["fcv_21"]

In [7]:
fcv_19 = pd.DataFrame(data["fcv_20"].tolist())

In [8]:
fcv_19.columns = ["fcv_19"]

In [9]:
X = data.drop(["fcv_19", "fcv_20", "fcv_21"], axis = 1)

In [10]:
X = pd.concat([X, fcv_19], axis = 1)

In [11]:
X

,location,use,heat,walls,roof,class,condition,quality,cool,landclass,...,garage_capa,patio_number,bath_fixture,stories,rooms,landmeas,fcv_16,fcv_17,fcv_18,fcv_19
0,102,8,8,3,7,2,0,0,1,0,...,0.0,0.0,3.0,1.0,3.0,3920.0,38000,45956,48305,70102
1,102,8,8,3,7,2,1,0,1,0,...,0.0,0.0,3.0,1.0,6.0,4760.0,75681,68113,71594,108011
2,102,8,1,3,7,2,0,0,1,1,...,0.0,1.0,3.0,1.0,5.0,1.0,81320,73188,76929,112637
3,102,8,1,4,1,2,0,0,1,1,...,0.0,1.0,3.0,1.0,5.0,1.0,97047,87342,91806,130794
4,102,8,6,2,1,2,1,0,1,0,...,1.0,1.0,3.0,1.0,5.0,1.0,84616,76154,80047,116660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101656,102,15,1,7,1,3,1,1,1,0,...,1.0,0.0,6.0,1.0,5.0,1.0,122159,122159,126724,162070
101657,102,8,1,2,1,2,0,0,1,1,...,0.0,0.0,3.0,1.0,4.0,1.0,71496,64346,67635,97082
101658,102,15,1,7,3,3,2,1,1,0,...,1.0,0.0,6.0,1.0,5.0,1.0,96747,96482,99815,127454
101659,102,15,1,2,3,3,1,1,1,0,...,1.0,1.0,3.0,1.0,4.0,1.0,92794,92794,96261,124338
101660,102,8,1,2,1,2,1,1,1,0,...,1.0,0.0,6.0,1.0,6.0,1.0,105133,94620,99456,144151

In [12]:
model = joblib.load("xgb_best.pkl")

In [13]:
predictions = model.predict(X)

In [14]:
np.sqrt(mean_squared_error(fcv_21, predictions))

14326.715701546646